/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaLogiin;

/**
 *
 * @author nonat
 */
public class TelaCadastramento extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastramento
     */
    public TelaCadastramento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgenda = new javax.swing.JButton();
        jButtonMedicos1 = new javax.swing.JButton();
        jButtonPaciente1 = new javax.swing.JButton();
        jLabelAgenda = new javax.swing.JLabel();
        jLabelPaciente = new javax.swing.JLabel();
        jLabelMedicos = new javax.swing.JLabel();
        jLabelSistemaDeCadastramento = new javax.swing.JLabel();
        jLabelPlanoDeFundoTelaCadastramento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonAgenda.setBackground(java.awt.SystemColor.textHighlight);
        jButtonAgenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAgenda.setForeground(new java.awt.Color(0, 102, 102));
        jButtonAgenda.setText("Agenda");
        getContentPane().add(jButtonAgenda);
        jButtonAgenda.setBounds(490, 240, 90, 23);

        jButtonMedicos1.setBackground(java.awt.SystemColor.textHighlight);
        jButtonMedicos1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonMedicos1.setForeground(new java.awt.Color(0, 102, 102));
        jButtonMedicos1.setText("Médicos");
        getContentPane().add(jButtonMedicos1);
        jButtonMedicos1.setBounds(260, 240, 90, 23);

        jButtonPaciente1.setBackground(java.awt.SystemColor.textHighlight);
        jButtonPaciente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonPaciente1.setForeground(new java.awt.Color(0, 102, 102));
        jButtonPaciente1.setText("Pacientes");
        jButtonPaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaciente1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPaciente1);
        jButtonPaciente1.setBounds(40, 240, 90, 23);

        jLabelAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IMAGEM ÍCONE AGENDA pq 2.JPG"))); // NOI18N
        getContentPane().add(jLabelAgenda);
        jLabelAgenda.setBounds(500, 160, 90, 60);

        jLabelPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/paciente5.JPG"))); // NOI18N
        getContentPane().add(jLabelPaciente);
        jLabelPaciente.setBounds(50, 150, 90, 80);

        jLabelMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ícone medicos 3.JPG"))); // NOI18N
        getContentPane().add(jLabelMedicos);
        jLabelMedicos.setBounds(240, 140, 130, 100);

        jLabelSistemaDeCadastramento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSistemaDeCadastramento.setForeground(new java.awt.Color(0, 102, 102));
        jLabelSistemaDeCadastramento.setText("SISTEMA DE CADASTRAMENTO ");
        getContentPane().add(jLabelSistemaDeCadastramento);
        jLabelSistemaDeCadastramento.setBounds(120, 50, 440, 30);

        jLabelPlanoDeFundoTelaCadastramento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3.jpg"))); // NOI18N
        getContentPane().add(jLabelPlanoDeFundoTelaCadastramento);
        jLabelPlanoDeFundoTelaCadastramento.setBounds(0, 0, 640, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaciente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPaciente1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastramento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonMedicos1;
    private javax.swing.JButton jButtonPaciente1;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelMedicos;
    private javax.swing.JLabel jLabelPaciente;
    private javax.swing.JLabel jLabelPlanoDeFundoTelaCadastramento;
    private javax.swing.JLabel jLabelSistemaDeCadastramento;
    // End of variables declaration//GEN-END:variables
}
